[0m22:59:10.358606 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C55FE310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C5E37790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C5BCDE90>]}


============================== 22:59:10.367405 | bc15bedc-6a8c-4090-aa69-992eb75dc9ad ==============================
[0m22:59:10.367405 [info ] [MainThread]: Running with dbt=1.11.0-b3
[0m22:59:10.372787 [debug] [MainThread]: running dbt with arguments {'no_print': 'None', 'printer_width': '80', 'profiles_dir': 'C:\\Users\\Ajaikumar\\.dbt', 'write_json': 'True', 'invocation_command': 'dbt init ga4_attribution', 'warn_error': 'None', 'static_parser': 'True', 'partial_parse': 'True', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'fail_fast': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_path': 'logs', 'use_experimental_parser': 'False', 'version_check': 'True', 'introspect': 'True', 'quiet': 'False', 'empty': 'None', 'log_cache_events': 'False', 'debug': 'False', 'log_format': 'default', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None'}
[0m22:59:10.443735 [debug] [MainThread]: Starter project path: D:\Data_Engineering\Projects\GA4_Attribution_Pipeline\venv\Lib\site-packages\dbt\include\starter_project
[0m22:59:10.474301 [info ] [MainThread]: 
Your new dbt project "ga4_attribution" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:59:10.477241 [info ] [MainThread]: Setting up your profile.
[0m23:00:28.738011 [info ] [MainThread]: Profile ga4_attribution written to C:\Users\Ajaikumar\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:00:28.743272 [debug] [MainThread]: Command `dbt init` succeeded at 23:00:28.742213 after 78.54 seconds
[0m23:00:28.744938 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C5E34F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C5E2C110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6BF379C10>]}
[0m23:00:28.748089 [debug] [MainThread]: Flushing usage events
[0m23:00:31.192658 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:19:02.869783 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B154F560D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B1585CE690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B1585CD350>]}


============================== 14:19:02.881458 | a93aeccf-0831-4478-ba51-a68981f6b04e ==============================
[0m14:19:02.881458 [info ] [MainThread]: Running with dbt=1.11.0-b3
[0m14:19:02.885838 [debug] [MainThread]: running dbt with arguments {'log_format': 'default', 'invocation_command': 'dbt run -s stg_streamed_events.sql+', 'printer_width': '80', 'profiles_dir': 'C:\\Users\\Ajaikumar\\.dbt', 'target_path': 'None', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'partial_parse': 'True', 'version_check': 'True', 'use_experimental_parser': 'False', 'introspect': 'True', 'quiet': 'False', 'empty': 'False', 'log_cache_events': 'False', 'debug': 'False', 'no_print': 'None', 'use_colors': 'True', 'cache_selected_only': 'False', 'write_json': 'True'}
[0m14:19:02.885838 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Data_Engineering\Projects\GA4_Attribution_Pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:19:02.891602 [debug] [MainThread]: Command `dbt run` failed at 14:19:02.891602 after 0.18 seconds
[0m14:19:02.891602 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B158237B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B1585FF450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B158342110>]}
[0m14:19:02.895605 [debug] [MainThread]: Flushing usage events
[0m14:19:05.036067 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:20:45.327400 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CBA5F05DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CBA5EC9390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CBA95C7F50>]}


============================== 14:20:45.336367 | 1c6d0d18-d457-4e4a-9541-aa0aaa834a3e ==============================
[0m14:20:45.336367 [info ] [MainThread]: Running with dbt=1.11.0-b3
[0m14:20:45.339345 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'no_print': 'None', 'invocation_command': 'dbt run -s ga4_attribution/models/stg_/stg_streamed_events.sql+', 'log_format': 'default', 'target_path': 'None', 'warn_error': 'None', 'indirect_selection': 'eager', 'fail_fast': 'False', 'log_path': 'logs', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'version_check': 'True', 'use_experimental_parser': 'False', 'quiet': 'False', 'introspect': 'True', 'empty': 'False', 'log_cache_events': 'False', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Ajaikumar\\.dbt', 'use_colors': 'True', 'cache_selected_only': 'False', 'write_json': 'True'}
[0m14:20:45.341358 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Data_Engineering\Projects\GA4_Attribution_Pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:20:45.346082 [debug] [MainThread]: Command `dbt run` failed at 14:20:45.346082 after 0.18 seconds
[0m14:20:45.346082 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CBA92179D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CBA95DA410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CBA957B390>]}
[0m14:20:45.349882 [debug] [MainThread]: Flushing usage events
[0m14:20:48.608259 [debug] [MainThread]: An error was encountered while trying to flush usage events
